spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=gcmm
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

firebase.service-account-path=${FIREBASE_SERVICE_ACCOUNT_PATH:/Users/gcmm/secrets/taskflow-firebase.json}
