-- Expand: novas colunas entram opcionais, sem quebrar linhas existentes
ALTER TABLE project ADD COLUMN key VARCHAR(20);
ALTER TABLE project ADD COLUMN next_task_number INTEGER NOT NULL DEFAULT 1;

ALTER TABLE task ADD COLUMN key VARCHAR(30);
ALTER TABLE task ADD COLUMN priority VARCHAR(20);

-- Backfill: preenche as linhas que já existiam antes da coluna existir
UPDATE project SET key = 'LEGACY' || id WHERE key IS NULL;
UPDATE task SET priority = 'MEDIUM' WHERE priority IS NULL;
UPDATE task
SET key = (SELECT p.key FROM project p WHERE p.id = task.project_id) || '-' || task.id
WHERE task.key IS NULL;

-- Contract: agora que toda linha tem valor, a constraint pode ser aplicada com segurança
ALTER TABLE project ALTER COLUMN key SET NOT NULL;
ALTER TABLE task ALTER COLUMN key SET NOT NULL;
ALTER TABLE task ALTER COLUMN priority SET NOT NULL;

CREATE TABLE task_labels (
    task_id BIGINT NOT NULL REFERENCES task (id),
    label VARCHAR(50) NOT NULL
);

CREATE TABLE comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000) NOT NULL,
    author_id BIGINT NOT NULL REFERENCES users (id),
    task_id BIGINT NOT NULL REFERENCES task (id),
    created_at TIMESTAMP NOT NULL
);
